// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFopEM1c8i3iVeqW9SWFhOykz9sLjmzPA',
    appId: '1:1032829149552:web:4fdb894b71121c37e4efb5',
    messagingSenderId: '1032829149552',
    projectId: 'apifatch1',
    authDomain: 'apifatch1.firebaseapp.com',
    storageBucket: 'apifatch1.appspot.com',
    measurementId: 'G-6RF0KBGSV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7Yo9YCGi1KUE0jC54i0ZZIJncHTNByQ',
    appId: '1:1032829149552:android:4d44f7b1b3841e48e4efb5',
    messagingSenderId: '1032829149552',
    projectId: 'apifatch1',
    storageBucket: 'apifatch1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqhWbPMC5oF6Dj-zRNf-Su4oCPajuOXs',
    appId: '1:1032829149552:ios:29a6a109132aff9be4efb5',
    messagingSenderId: '1032829149552',
    projectId: 'apifatch1',
    storageBucket: 'apifatch1.appspot.com',
    iosBundleId: 'com.example.audioTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFopEM1c8i3iVeqW9SWFhOykz9sLjmzPA',
    appId: '1:1032829149552:web:4fdb894b71121c37e4efb5',
    messagingSenderId: '1032829149552',
    projectId: 'apifatch1',
    authDomain: 'apifatch1.firebaseapp.com',
    storageBucket: 'apifatch1.appspot.com',
    measurementId: 'G-6RF0KBGSV7',
  );

}